--[[
entropoy.mac
list_spa.lua

list of SPA and IDs
--]]


mq = require('mq')
local args = {...}
local spa = {}

spa[0] "HP"                    
spa[1] "AC"                    
spa[2] "Attack Power"          
spa[3] "Movement Rate"         
spa[4] "STR"                   
spa[5] "DEX"                   
spa[6] "AGI"                   
spa[7] "STA"                   
spa[8] "INT"                   
spa[9] "WIS"                   
spa[10] "CHA"                  
spa[11] "Melee Speed"          
spa[12] "Invisibility"         
spa[13] "See Invis"            
spa[14] "Enduring Breath"      
spa[15] "Mana"                 
spa[16] "NPC-Frenzy"           
spa[17] "NPC-Awareness"        
spa[18] "NPC Aggro"            
spa[19] "NPC Faction"          
spa[20] "Blindness"            
spa[21] "Stun"                 
spa[22] "Charm"                
spa[23] "Fear"                 
spa[24] "Fatigue"              
spa[25] "Bind Affinity"        
spa[26] "Gate"                 
spa[27] "Dispel Magic"         
spa[28] "Invis Vs Undead"      
spa[29] "Invis Vs Animals"     
spa[30] "NPC-ReactRange"       
spa[31] "Enthrall (Mez)"       
spa[32] "Create Item"          
spa[33] "Spawn NPC"            
spa[34] "Confuse"              
spa[35] "Disease"              
spa[36] "Poison"               
spa[37] "DetectHostile"        
spa[38] "DetectMagic"          
spa[39] "NoTwincast"           
spa[40] "Invulnerability"      
spa[41] "Banish"               
spa[42] "Shadow Step"          
spa[43] "Berserk"              
spa[44] "Lycanthropy"          
spa[45] "Vampirism"            
spa[46] "Resist Fire"          
spa[47] "Resist Cold"          
spa[48] "Resist Poison"        
spa[49] "Resist Disease"       
spa[50] "Resist Magic"         
spa[51] "Detect (Switch) Traps"
spa[52] "Detect Undead"        
spa[53] "Detect Summoned"      
spa[54] "Detect Animals"       
spa[55] "Stoneskin"            
spa[56] "True North"           
spa[57] "Levitation"           
spa[58] "Change Form"          
spa[59] "Damage Attackers (DS)"
spa[60] "TransferItem"         
spa[61] "Identify"             
spa[62] "Item ID"              
spa[63] "NPC-WipeHatelist"     
spa[64] "Spin Stun"            
spa[65] "Infravision"          
spa[66] "Ultravision"          
spa[67] "NPC-POV"              
spa[68] "Reclaim Energy"       
spa[69] "Max HP"               
spa[70] "CorpseBomb"           
spa[71] "Create Undead"        
spa[72] "PreserveCorpse"       
spa[73] "TargetsView"          
spa[74] "FeignDeath"           
spa[75] "Ventriloquism"        
spa[76] "Sentinel"             
spa[77] "LocateCorpse"         
spa[78] "SpellShield"          
spa[79] "InstantHP"            
spa[80] "Enchant:Light"        
spa[81] "Resurrect"            
spa[82] "Summon Target"        
spa[83] "Portal"               
spa[84] "Hp-NPC-ONLY"          
spa[85] "Contact Ability (Melee Proc)"
spa[86] "NPC-Help-Radius"      
spa[87] "Telescope"            
spa[88] "Combat Portal"        
spa[89] "Height"               
spa[90] "IgnorePet"            
spa[91] "SummonCorpse"         
spa[92] "Hate (On Spell Land)" 
spa[93] "WeatherControl"       
spa[94] "Fragile"              
spa[95] "Sacrifice"            
spa[96] "Silence"              
spa[97] "Max Mana"             
spa[98] "Bard Haste"           
spa[99] "Root"                 
spa[100] "HP Duration Only"    
spa[101] "Complete Heal (Residual Buff)"
spa[102] "Pet No Fear"         
spa[103] "Summon Pet"          
spa[104] "Translocate"         
spa[105] "Anti-Gate (NPC Only)"
spa[106] "BeastLordPet"        
spa[107] "Alter Pet Level"     
spa[108] "Familiar"            
spa[109] "CreateItemInBag"     
spa[110] "Removed (Archery RNG Acc%)"
spa[111] "Resistances"         
spa[112] "Adjust Casting Skill (Fizzles)"
spa[113] "SummonMount"         
spa[114] "Modify Hate"         
spa[115] "Cornucopia"          
spa[116] "Curse"               
spa[117] "HitMagic"            
spa[118] "Amplification"       
spa[119] "BardHaste2"          
spa[120] "HealMod"             
spa[121] "IronMaiden"          
spa[122] "ReduceSkill"         
spa[123] "Immunity"            
spa[124] "Fc_Damage_%"         
spa[125] "Fc_HealMod"          
spa[126] "Fc_ResistMod"        
spa[127] "Fc_CastTimeMod1"     
spa[128] "Fc_DurationMod"      
spa[129] "Fc_RangeMod"         
spa[130] "Fc_HateMod"          
spa[131] "Fc_ReagentMod"       
spa[132] "Fc_ManaMod"          
spa[133] "Fc_StunTimeMod"      
spa[134] "Ff_LevelMax"         
spa[135] "Ff_ResistType"       
spa[136] "Ff_TargetType"       
spa[137] "Ff_WhichSPA"         
spa[138] "Ff_Beneficial"       
spa[139] "Ff_WhichSpellID"     
spa[140] "Ff_DurationMin"      
spa[141] "Ff_InstantOnly"      
spa[142] "Ff_LevelMin"         
spa[143] "Ff_CastTimeMin"      
spa[144] "Ff_CastTimeMax"      
spa[145] "Portal NPC Warder Banish"
spa[146] "Portal Locations"    
spa[147] "Percent Heal"        
spa[148] "StackingBlocker"     
spa[149] "StripVirtualSlot"    
spa[150] "Divine Intervention/Death Pact"
spa[151] "PocketPet"           
spa[152] "PetSwarm"            
spa[153] "Damage Balance"      
spa[154] "Cancel Negative"     
spa[155] "PoP Resurrect"       
spa[156] "Mirror Form"         
spa[157] "Feedback"            
spa[158] "Reflect"             
spa[159] "Mod all Stats"       
spa[160] "Inebriation | Sobriety"
spa[161] "Spell Guard"         
spa[162] "Melee Guard"         
spa[163] "Absorb Hit"          
spa[164] "Object - Sense Trap" 
spa[165] "Object - Disarm Trap"
spa[166] "Object - Picklock"   
spa[167] "Fc_Pet"              
spa[168] "Defensive"           
spa[169] "Critical Melee (PC Only)"
spa[170] "Spell Crit Damage"   
spa[171] "Crippling Blow"      
spa[172] "Evasion"             
spa[173] "Riposte"             
spa[174] "Dodge"               
spa[175] "Parry"               
spa[176] "Dual Wield"          
spa[177] "Double Attack"       
spa[178] "Melee Resource Drain"
spa[179] "Puretone"            
spa[180] "Sanctification"      
spa[181] "Fearless"            
spa[182] "Hundred Hands"       
spa[183] "UNUSED Skill Increase Chance"
spa[184] "Accuracy %"          
spa[185] "Skill Damage Mod 1"  
spa[186] "Min Damage Done Mod" 
spa[187] "Mana Balance"        
spa[188] "Block"               
spa[189] "Endurance"           
spa[190] "Max Endurance"       
spa[191] "Amnesia"             
spa[192] "Hate (Duration Only)"
spa[193] "Skill Attack"        
spa[194] "Fade"                
spa[195] "Stun Resist (Melee+Spell)"
spa[196] "Deprecated (strikethrough)"
spa[197] "Skill Damage Taken Incoming"
spa[198] "Instant Endurance"   
spa[199] "Taunt"               
spa[200] "Weapon Proc Chance"  
spa[201] "Ranged Proc"         
spa[202] "IllusionOther"       
spa[203] "MassBuff"            
spa[204] "Group Fear Immunity" 
spa[205] "AE Rampage Instant (PC Only)"
spa[206] "AE Taunt"            
spa[207] "Flesh to Bone"       
spa[208] "Purge Poison"        
spa[209] "Cancel Beneficial"   
spa[210] "Shield Caster"       
spa[211] "AE Melee (PC Only)"  
spa[212] "Fc_FrenziedDevastation"
spa[213] "Pet % HP"            
spa[214] "HP Max Percent"      
spa[215] "Pet Avoidance %"     
spa[216] "Melee Accuracy Amt"  
spa[217] "Headshot"            
spa[218] "Pet Crit Melee Chance (Owner)"
spa[219] "Slay Undead"         
spa[220] "Skill Min_Damage Amt 1"
spa[221] "ReduceWeight"        
spa[222] "BlockBehind"         
spa[223] "Double Riposte"      
spa[224] "AddRiposte"          
spa[225] "Give Double Attack"  
spa[226] "2hbash"              
spa[227] "ReduceSkillTimer"    
spa[228] "ReduceFallDmg"       
spa[229] "CastThroughStun"     
spa[230] "Increase Shield Distance"
spa[231] "StunBashChance"      
spa[232] "Divine Save"         
spa[233] "Metabolism"          
spa[234] "Poison Mastery"      
spa[235] "FocusChannelling"    
spa[236] "Free Pet"            
spa[237] "PetAffinity"         
spa[238] "Permanent Illusion"  
spa[239] "Stonewall"           
spa[240] "String Unbreakable"  
spa[241] "Improve Reclaim Energy"
spa[242] "IncreaseChanceMemwipe"
spa[243] "NoBreakCharmChance"  
spa[244] "RootBreakChance"     
spa[245] "Trap Circumvention"  
spa[246] "Lung Capacity"       
spa[247] "IncreaseSkillCap"    
spa[248] "ExtraSpecialization" 
spa[249] "Offhand Weapon MinDamage Bonus"
spa[250] "Increase ContactAbility Chance"
spa[251] "EndlessQuiver"       
spa[252] "Backstab FullDamage From Front"
spa[253] "Chaotic Stab"        
spa[254] "NoSpell"             
spa[255] "Shielding Duration Mod"
spa[256] "Shroud of Stealth"   
spa[257] "DEPRECATED GivePetHold"
spa[258] "Triple Backstab"     
spa[259] "ACLimitMod"          
spa[260] "AddInstrumentMod"    
spa[261] "SongModCap"          
spa[262] "StatsCap"            
spa[263] "TradeskillMasteries" 
spa[264] "ReduceAATimer"       
spa[265] "NoFizzle"            
spa[266] "AddExtraAttack% (2h)"
spa[267] "AddPetCommands"      
spa[268] "AlcFailRate"         
spa[269] "Bandage Max HP Limit %"
spa[270] "Bard Song Beneficial Radius %"
spa[271] "BaseRunMod"          
spa[272] "Bard Song Level"     
spa[273] "Critical DoT"        
spa[274] "CriticalHeal"        
spa[275] "Critical Mend %"     
spa[276] "DualWieldAmt"        
spa[277] "ExtraDIChance"       
spa[278] "FinishingBlow"       
spa[279] "FlurryChance (PC Only)"
spa[280] "Pet Flurry Chance (Owner)"
spa[281] "GivePetFeign"        
spa[282] "Increase Bandage Heal %"
spa[283] "SpecialAttackChain"  
spa[284] "LoHSetHeal"          
spa[285] "Allow Hide/Evade While Moving"
spa[286] "Fc_Damage_Amt"       
spa[287] "Fc_DurationMod (static)"
spa[288] "Add Proc Hit (AA)"   
spa[289] "Doom Duration"       
spa[290] "Increase Movement Cap"
spa[291] "Purify"              
spa[292] "Strikethrough"       
spa[293] "StunResist2 (Melee)" 
spa[294] "Spell Crit Chance"   
spa[295] "ReduceTimerSpecial"  
spa[296] "Fc_Spell_Damage_%_Incoming"
spa[297] "Fc_Spell_Damage_Amt_Incoming"
spa[298] "Height (Small)"      
spa[299] "Wake the Dead 1 (Corpse Class)"
spa[300] "Doppelganger"        
spa[301] "Increase Range Damage"
spa[302] "Fc_Damage_%_Crit"    
spa[303] "Fc_Damage_Amt_Crit"  
spa[304] "Secondary Riposte Mod"
spa[305] "Mitigate Damage Shield Offhand"
spa[306] "Wake the Dead 2 (File Class)"
spa[307] "Appraisal"           
spa[308] "Zone Suspend Minion" 
spa[309] "Teleport Caster's Bindpoint"
spa[310] "Fc_ReuseTimer"       
spa[311] "Ff_CombatSkill"      
spa[312] "Observer"            
spa[313] "Forage Master"       
spa[314] "Improved Invis"      
spa[315] "Improved Invis Undead"
spa[316] "Improved Invis Animals"
spa[317] "Worn Regen Cap"      
spa[318] "Worn Mana Regen Cap" 
spa[319] "Critical HP Regen"   
spa[320] "Shield Block Chance" 
spa[321] "Reduce Target Hate"  
spa[322] "Gate Starting City"  
spa[323] "Defensive Proc"      
spa[324] "HP for Mana"         
spa[325] "No Break AE Sneak"   
spa[326] "Spell Slots"         
spa[327] "Buff Slots"          
spa[328] "Negative HP Limit"   
spa[329] "Mana Absorb % Damage"
spa[330] "Critical Melee Damage Mod"
spa[331] "Alchemy Item Recovery"
spa[332] "Summon to Corpse"    
spa[333] "Doom Rune Consumed"  
spa[334] "HP No Move"          
spa[335] "Fc_Immunity_Focus"   
spa[336] "Illusionary Target"  
spa[337] "Increase Exp %"      
spa[338] "Expedient Recovery"  
spa[339] "Fc_CastProc"         
spa[340] "Chance Spell"        
spa[341] "Worn Attack Cap"     
spa[342] "No Panic"            
spa[343] "Spell Interrupt"     
spa[344] "Item Channeling"     
spa[345] "Assassinate Max Level / Chance"
spa[346] "Headshot Max"        
spa[347] "Double Ranged Attack"
spa[348] "Ff_Mana_Min"         
spa[349] "Increase Damage With Shield"
spa[350] "Manaburn"            
spa[351] "Spawn Interactive Object"
spa[352] "Increase Trap Count" 
spa[353] "Increase SOI Count"  
spa[354] "Deactivate All Traps"
spa[355] "Learn Trap"          
spa[356] "Change Trigger Type" 
spa[357] "Fc_Mute"             
spa[358] "Instant Mana"        
spa[359] "Passive Sense Trap"  
spa[360] "Proc On Kill Shot"   
spa[361] "Proc On Death"       
spa[362] "Potion Belt"         
spa[363] "Bandolier"           
spa[364] "AddTripleAttackChance"
spa[365] "Proc On Spell Kill Shot"
spa[366] "Group Shielding"     
spa[367] "Modify Body Type"    
spa[368] "Modify Faction"      
spa[369] "Corruption"          
spa[370] "ResistCorruption"    
spa[371] "Slow"                
spa[372] "Grant Foraging"      
spa[373] "Doom Always"         
spa[374] "Trigger Spell"       
spa[375] "Critical DoT Damage Mod %"
spa[376] "Fling"               
spa[377] "Removed (Doom Entity)"
spa[378] "Resist Other SPA"    
spa[379] "Directional Shadowstep"
spa[380] "Knockback Explosive (PC Only)"
spa[381] "Fling Target to Caster"
spa[382] "Suppression"         
spa[383] "Fc_CastProcNormalized"
spa[384] "Fling Caster to Target"
spa[385] "Ff_WhichSpellGroup"  
spa[386] "Doom Dispeller"      
spa[387] "Doom Dispelled"      
spa[388] "Summon All Corpses"  
spa[389] "Fc_Timer_Refresh"    
spa[390] "Fc_Timer_Lockout"    
spa[391] "Ff_Mana_Max"         
spa[392] "Fc_Heal_Amt"         
spa[393] "Fc_Heal_%_Incoming"  
spa[394] "Fc_Heal_Amt_Incoming"
spa[395] "Fc_Heal_%_Crit"      
spa[396] "Fc_Heal_Amt_Crit"    
spa[397] "Pet Add AC"          
spa[398] "Fc_Swarm_Pet_Duration"
spa[399] "Fc_Twincast"         
spa[400] "Healburn"            
spa[401] "Mana Ignite"         
spa[402] "Endurance Ignite"    
spa[403] "Ff_SpellClass"       
spa[404] "Ff_SpellSubclass"    
spa[405] "Staff Block Chance"  
spa[406] "Doom Limit Use"      
spa[407] "Doom Focus Used"     
spa[408] "Limit HP"            
spa[409] "Limit Mana"          
spa[410] "Limit Endurance"     
spa[411] "Ff_ClassPlayer"      
spa[412] "Ff_Race"             
spa[413] "Fc_BaseEffects"      
spa[414] "Ff_CastingSkill"     
spa[415] "Ff_ItemClass"        
spa[416] "AC_2"                
spa[417] "Mana_2"              
spa[418] "Skill Min_Damage Amt 2"
spa[419] "Contact Ability 2 (Melee Proc)"
spa[420] "Fc_Limit_Use"        
spa[421] "Fc_Limit_Use_Amt"    
spa[422] "Ff_Limit_Use_Min"    
spa[423] "Ff_Limit_Use_Type"   
spa[424] "Gravitate"           
spa[425] "Fly"                 
spa[426] "AddExtTargetSlots"   
spa[427] "Skill Proc (Attempt)"
spa[428] "Proc Skill Modifier" 
spa[429] "Skill Proc (Success)"
spa[430] "PostEffect"          
spa[431] "PostEffectData"      
spa[432] "ExpandMaxActiveTrophyBenefits"
spa[433] "Normalized Skill Min_Dmg Amt 1"
spa[434] "Normalized Skill Min_Dmg Amt 2"
spa[435] "Fragile Defense"     
spa[436] "Toggle Freeze Buff Timers"
spa[437] "Teleport to Anchor"  
spa[438] "Translocate to Anchor"
spa[439] "Assassinate Chance / DMG"
spa[440] "FinishingBlowMax"    
spa[441] "Distance Removal"    
spa[442] "Doom Req Bearer"     
spa[443] "Doom Req Caster"     
spa[444] "Improved Taunt"      
spa[445] "Add Merc Slot"       
spa[446] "A_Stacker"           
spa[447] "B_Stacker"           
spa[448] "C_Stacker"           
spa[449] "D_Stacker"           
spa[450] "DoT Guard"           
spa[451] "Melee Threshold Guard"
spa[452] "Spell Threshold Guard"
spa[453] "Doom Melee Threshold"
spa[454] "Doom Spell Threshold"
spa[455] "Add Hate % (On Land)"
spa[456] "Add Hate Over Time %"
spa[457] "Resource Tap"        
spa[458] "Faction Mod %"       
spa[459] "Skill Damage Mod 2"  
spa[460] "Ff_Override_NotFocusable"
spa[461] "Fc_Damage_%_Crit 2"  
spa[462] "Fc_Damage_Amt 2"     
spa[463] "Shield Target"       
spa[464] "PC Pet Rampage"      
spa[465] "PC Pet AE Rampage"   
spa[466] "PC Pet Flurry Chance"
spa[467] "DS Mitigation Amount"
spa[468] "DS Mitigation Percentage"
spa[469] "Chance Best in Spell Group"
spa[470] "Trigger Best in Spell Group"
spa[471] "Double Melee Round (PC Only)"
spa[472] "Buy AA Rank"         
spa[473] "Double Backstab From Front"
spa[474] "Pet Crit Melee Damage% (Owner)"
spa[475] "Trigger Spell Non-Item"
spa[476] "Weapon Stance"       
spa[477] "Hatelist To Top Index"
spa[478] "Hatelist To Tail Index"
spa[479] "Ff_Value_Min"        
spa[480] "Ff_Value_Max"        
spa[481] "Fc_Cast_Spell_On_Land"
spa[482] "Skill Base Damage Mod"
spa[483] "Fc_Spell_Damage_%_IncomingPC"
spa[484] "Fc_Spell_Damage_Amt_IncomingPC"
spa[485] "Ff_CasterClass"      
spa[486] "Ff_Same_Caster"      
spa[487] "Extend Tradeskill Cap"
spa[488] "Defender Melee Force % (PC)"
spa[489] "Worn Endurance Regen Cap"
spa[490] "Ff_ReuseTimeMin"     
spa[491] "Ff_ReuseTimeMax"     
spa[492] "Ff_Endurance_Min"    
spa[493] "Ff_Endurance_Max"    
spa[494] "Pet Add Atk"         
spa[495] "Ff_DurationMax"      
spa[496] "Critical Melee Damage Mod Max"
spa[497] "Ff_FocusCastProcNoBypass"
spa[498] "AddExtraAttack% (1h-Primary)"
spa[499] "AddExtraAttack% (1h-Secondary)"
spa[500] "Fc_CastTimeMod2"     
spa[501] "Fc_CastTimeAmt"      
spa[502] "Fearstun"            
spa[503] "Melee Damage Position Mod"
spa[504] "Melee Damage Position Amt"
spa[505] "Damage Taken Position Mod"
spa[506] "Damage Taken Position Amt"
spa[507] "Fc_Amplify_Mod"      
spa[508] "Fc_Amplify_Amt"      
spa[509] "Health Transfer"     
spa[510] "Fc_ResistIncoming"   
spa[511] "Ff_FocusTimerMin"    
spa[512] "Proc Timer Modifier" 
spa[513] "Mana Max Percent"    
spa[514] "Endurance Max Percent"
spa[515] "AC Avoidance Max Percent"
spa[516] "AC Mitigation Max Percent"
spa[517] "Attack Offense Max Percent"
spa[518] "Attack Accuracy Max Percent"
spa[519] "Luck Amount"         
spa[520] "Luck Percent"        
         
         
return spa[args[1]]                                         